language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer selfupdate
  - composer install --prefer-source

script: 
  - phpunit --coverage-text --coverage-clover /tmp/thibaud-evaneos/dicitools/coverage.xml
  - php ocular.phar code-coverage:upload --format=php-clover /tmp/evaneos/dicitools/coverage.xml
  - ./vendor/bin/phpcs --standard=./phpcs.xml -n --report=gitblame ./src
